@Test public void testCreateNumber() throws Exception { assertEquals(1, NumberUtils.createNumber("1")); assertEquals(2, NumberUtils.createNumber("2")); assertEquals(3, NumberUtils.createNumber("3")); assertEquals(4, NumberUtils.createNumber("4")); assertEquals(5, NumberUtils.createNumber("5")); assertEquals(6, NumberUtils.createNumber("6")); assertEquals(7, NumberUtils.createNumber("7")); assertEquals(8, NumberUtils.createNumber("8")); assertEquals(9, NumberUtils.createNumber("9")); assertEquals(null, NumberUtils.createNumber(null));}